### ISSUE TITLE
prog_uint8_t typedef is deprecated

### ISSUE THREAD

**Issue by lukedubber** [sparkfun/SevSeg#10]
On [line 39](https://github.com/sparkfun/SevSeg/blob/master/Libraries/SevSeg/SevSeg.h#L39) of SevSeg.h this prog_unit8_t typedef is deprecated. Tested on Arduino IDE 1.6.0.

Fixed the issue by putting this line aboe
```c
typedef uint8_t PROGMEM prog_uint8_t;
```

Credit goes to emueyes from [your forms](https://forum.sparkfun.com/viewtopic.php?f=14&t=37101#p166012)

Was doing the [bubble display hookup guide](https://learn.sparkfun.com/tutorials/bubble-display-hookup-guide).

Thanks!

**Comment by jimblom** [comment]
Thanks for making us aware of this. Fixed!
