### ISSUE TITLE
Maybe README.md should point to compatible Sparkfun products

### ISSUE THREAD

**Issue by q2dg** [sparkfun/SevSeg#12]
It seems they are nº 9480, nº 9481, nº 9482 and nº 9483 , but it isn't clear
In fact, in their respective product page this library isn't even mentioned.
Thanks

**Comment by q2dg** [comment]
Well, in source code is pointed to product nº 11408, which only has 12 pins, as README.md states (9480/1/2/3 have 16). So it seems I was wrong and this library is only compatible with 11408 product...Well, README.md should clarify this.
Thanks

**Comment by ToniCorinne** [comment]
Thanks for the feedback. I've added a link to the hookup guide for the serial displays (that uses additional code), and also to a wishlist with compatible products.

**Comment by q2dg** [comment]
You're welcome!
